#spring.application.name=demo
#spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring:
 datasource:
  url: jdbc:postgresql://localhost:5433/jwt_security
  username: postgres
  password: 123456
  driver-class-name: org.postgresql.Driver
 jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect



